; You do not need to include every line or field. Each matching plugin completely replaces the built-in version embedded in the DLL. 
;
; IncludeForms=FormID1,FormID2,FormID3
; Optional. When omitted or empty, all dialogue is included.
; When populated, VDT tags ONLY the specified dialogue entries.
;
; ExcludeForms=FormID1,FormID2,FormID3
; Optional. When omitted or empty, no dialogue is excluded.
; When populated, VDT excludes the specified dialogue entries.
;
; FormIDs may optionally use the 0x prefix.
; See sasnikol's "FormIDs and You":
; https://www.nexusmods.com/skyrimspecialedition/articles/6629
; Example valid FormIDs: 00000D6B, 0x00D6B, 0xD6B

[General]
; This controls whether any dialogue is tagged at all.
Enabled=true

; Default: GlobalPluginNameFallback=false
; When true, automatically generates missing tags based on plugin filename.
GlobalPluginNameFallback=false

HideTagsWhenAllOptionsMatch=false

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;; Place custom rules below ;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Adds [FirstTag][SecondTag], note that brackets are added automatically:
[Plugin:ExampleModThatIHopeIsntReal1.esp]
Tag=FirstTag][SecondTag
IncludeForms=
ExcludeForms=
ModNameTags=

; VDT will also accept bracketed tags, but again, providing opening & closing brackets are unnecessary:
[Plugin:ExampleModThatIHopeIsntReal3.esp]
Tag=[YesThisTagWorks]

; And this example will prevent a mod from being tagged:
[Plugin:ExampleModThatIHopeIsntReal2.esp]
ModNameTags=false
