; Each matching plugin section completely replaces the built-in version. You do not need to include every line/field.
	; IncludeForms=FormID1,FormID2, FormID3
	;		Defaults to including all dialogue. Defaults if line not present, or empty field.
	;		Entries will cause VDT to tag *only* the specified entries. Spaces after commas in list are optional.
	; ExcludeForms=FormID1,FormID2, FormID3
	;		Defaults to nothing being excluded. Defaults if line not present, or empty field.
	;		Entries will cause VDT to exclude the specified entries. Spaces after commas in list are optional.
	; You will need FormIDs for IncludeForms/ExcludeForms.
	;		Please see sasnikol's "FormIDs and You" for general information regarding FormIDs: https://www.nexusmods.com/skyrimspecialedition/articles/6629
	;		However, as an example, VDT accepts all of these FormIDs from Immersive Wenches v1.6 (an ESP, NOT ESL-flagged): 00000D6B, 0x00D6B, 0xD6B

[General]
Enabled=true
GlobalPluginNameFallback=false
; 	GlobalPluginNameFallback will automatically tag every line from every mod, using mod's plugin name if not explicitly tagged/supported in this INI or by VDT's embedded built-in rules.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;; Place custom rules below ;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; This complete example will add [FirstTag][SecondTag] tags (note, uses brackets):
[Plugin:ExampleModThatIHopeIsntReal1.esp]
Tag=[FirstTag][SecondTag]
IncludeForms=
ExcludeForms=
ModNameTags=

; This complete example will remove tags:
[Plugin:ExampleModThatIHopeIsntReal2.esp]
ModNameTags=false

; COPY THIS ONE FOR SIMPLICITY; this complete example will add [YesThisTagWorks] tags (note, doesn't require brackets):
[Plugin:ExampleModThatIHopeIsntReal3.esp]
Tag=YesThisTagWorks

