; All lines/fields are optional. Plugin sections only override the lines/settings you include.
; In [Plugin: ...] sections, including a line with a blank/empty value "clears" the built-in value.
;
; You can put plugin rules in this file, or create new files named VariousDialogueTags_*.ini (replace * with any name you want).
; [Plugin:ExampleModThatIHopeIsntReal3.esp]
; Tag=FirstTag][SecondTag      //    Outer brackets are automatically added.
; ModNameTags=true/false       //    Set 'false' to disable tags for this plugin. Defaults true.
; IncludeForms=D6B,00000E6C    //    When populated, tags ONLY the specified entries.
; ExcludeForms=000A0C,0xD5A    //    When populated, excludes the specified entries.
;
; FormID 0x and leading zeroes are optional.
; Example: D6B, 00000D6B, and 0xD6B are all equivalent.

[General]
; Explicit/user-defined values are cached on gamestart. DEFAULT inherits cached values (so your values are persistent across updates).

; This controls whether any dialogue is tagged at all. Default: Enabled=true
Enabled=DEFAULT

; When true, automatically generates missing tags based on plugin filename. Default: GlobalPluginNameFallback=false
GlobalPluginNameFallback=DEFAULT

; Hides tags if all tags in dialogue menu are matching. Tags will only appear when different tags/mods are present in the same menu. Default: ImmersiveMode=false
ImmersiveMode=DEFAULT

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;; Example custom rules ;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Prevents plugin from being tagged:
[Plugin:ExampleModThatIHopeIsntReal2.esp]
ModNameTags=false

; Changes or sets a plugin's tag:
[Plugin:ExampleModThatIHopeIsntReal1.esp]
Tag=Custom Tag
